on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on merge to main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Create temporary SSH key file
        id: ssh-key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ssh_key.pem
          chmod 400 ssh_key.pem
          echo "::set-output name=filename::ssh_key.pem"

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ steps.ssh-key.outputs.filename }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Send Slack notification
        if: ${{ success() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Workflow successful. Starting git pull origin main."}' $SLACK_WEBHOOK

      - name: SSH into Server 1 and perform git pull
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ steps.ssh-key.outputs.filename }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          RUN: git pull origin main

      - name: Remove temporary SSH key file
        run: |
            rm ${{ steps.ssh-key.outputs.filename }}|
            echo "removed"
