on:
  pull_request_target:
    types: closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set permission for the repository
        run: chmod -R 755 .

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: .

      - name: Get modified files
        id: files
        run: |
          echo "::set-output name=files::$(git diff --name-only origin/main...${{ github.event.pull_request.head.sha }})"

      - name: Send Slack notification
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          FILES="${{ steps.files.outputs.files }}"
          MESSAGE="{\"text\":\"Merged branch: ${BRANCH_NAME}\nPulling changes from: main\nModified files: ${FILES}\"}"
          curl -X POST -H 'Content-type: application/json' --data "$MESSAGE" ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: SSH into Server 1 and perform git pull
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: .
          RUN: |
            git pull origin main
            echo "Successfully updated local with remote changes"
